let diaDaSemana = 6

if (diaDaSemana == 0){
    console.log("Comer");
    console.log("Dormir");
    console.log("Jogar");
}
else if(diaDaSemana == 1){
    console.log("Trabalhar");
    console.log("Jogar");
    console.log("IOS");
}
else if(diaDaSemana == 2){
    console.log("Trabalhar");
    console.log("CNA");
    console.log("IOS");
}
else if(diaDaSemana == 3){
    console.log("Trabalhar");
    console.log("Jogar");
    console.log("IOS");
}
else if(diaDaSemana == 4){
    console.log("Trabalhar");
    console.log("CNA");
    console.log("IOS");
}
else if(diaDaSemana == 5){
    console.log("IOS");
    console.log("Jogar");
    console.log("Volêi");
}
else if(diaDaSemana == 6){
    console.log("Tomar banho");
    console.log("Jogar");
    console.log("Comer churros");
}